# version: 2
# sources:
#   - name: pharma_project
#     schema: p_transformed_sch
#     tables:
#       - name: date_dimension
#         description: "Date dimension table loaded from the CSV seed file."
